version: '2'
services:
  web:
    build: .
    depends_on:
      - $REDIS_CONTAINER_NAME
    ports:
      - $APP_HOST_PORT:$APP_GUEST_PORT
    links:
      - $REDIS_CONTAINER_NAME
    env_file:
      - ./.env-guest
    logging:
      driver: json-file
  grape-redis:
    image: $REDIS_IMAGE_NAME
    ports:
      - $REDIS_PORT:$REDIS_PORT