default: &default
  boot:
    scan:
      directories:
        - app/formatters
        - app/entities
        - app/entities/params
        - app/middlewares
        - app/models
        - app/providers
        - app/helpers/http
        - app/helpers
        - app/apis
        - lib/features
        - app/
  db:
    location: config/database.yml
  apis:
    developers:
      enabled: true
    projects:
      enabled: false
  helpers:
    pagination_helper:
      per_page: 10
      max_per_page: 30
    developers_helper:
      cache_key_prefix: 'developer:'
      cache_expiration: 30
  middlewares:
    auth:
      credentials:
        marioluan: '123456'
        joaosilva: abcdef
  logger:
    level:
      default: 0
  features:
    cache:
      enabled: false
  swagger:
    info:
      title: RESTFul API
      description: Example of a restful api using grape framework.
      contact: mariosouzaluan@gmail.com
development:
  <<: *default
test:
  <<: *default
  logger:
    level:
      default: 5
qa:
  <<: *default
stagging:
  <<: *default
production:
  <<: *default