default: &default
  boot:
    scan:
      directories:
        - config/initializers
        - app/formatters
        - app/entities
        - app/entities/params
        - app/middlewares
        - app/models
        - app/providers
        - app/helpers
        - app/apis
        - app/
  apis:
    developers:
      enabled: true
    projects:
      enabled: false
  helpers:
    pagination_helper:
      per_page:
        default: 10
      page:
        default: 0
    developers_helper:
      cache_key_prefix: 'developer:'
      cache_expiration: 30
development:
  <<: *default
test:
  <<: *default
qa:
  <<: *default
stagging:
  <<: *default
production:
  <<: *default